<?php

use App\Models\SurfacewaterMonthly;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DustController;
use App\Http\Controllers\BiotaController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\NoiseController;
use App\Http\Controllers\AmbienController;
use App\Http\Controllers\MarineController;
use App\Http\Controllers\StdBlastingTable;
use App\Http\Controllers\TailingController;
use App\Http\Controllers\AuthDustController;
use App\Http\Controllers\AuthGroundWaterMSM;
use App\Http\Controllers\AuthGroundWaterTTN;
use App\Http\Controllers\BlastingController;
use App\Http\Controllers\EmissionController;
use App\Http\Controllers\RainfallController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\AuthNoiseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Emission2Controller;
use App\Http\Controllers\HydroCodeController;
use App\Http\Controllers\AuthMarineController;
use App\Http\Controllers\DrinkWaterController;
use App\Http\Controllers\FreshWaterController;
use App\Http\Controllers\GwStandardController;
use App\Http\Controllers\WastewaterController;
use App\Http\Controllers\EvaporationController;
use App\Http\Controllers\HydrometricController;
use App\Http\Controllers\SoilQualityController;
use App\Http\Controllers\AuthBlastingController;
use App\Http\Controllers\CodeSampleNMController;
use App\Http\Controllers\AmbienPointidController;
use App\Http\Controllers\AuthWellLevelController;
use App\Http\Controllers\DashboardAuthController;
use App\Http\Controllers\LocationBiotaController;
use App\Http\Controllers\LocationNoiseController;
use App\Http\Controllers\PointIdMarineController;
use App\Http\Controllers\StdDrinkWaterController;
use App\Http\Controllers\TailingCodeIdController;
use App\Http\Controllers\AuthFreshwaterController;
use App\Http\Controllers\DischargeManualController;
use App\Http\Controllers\EmissionPointIdController;
use App\Http\Controllers\PointIdBlastingController;
use App\Http\Controllers\QualityStandardController;
use App\Http\Controllers\RainfallPointIdController;
use App\Http\Controllers\TailingStandardController;
use App\Http\Controllers\AmbienQualityStdController;
use App\Http\Controllers\AuthSurfaceWaterController;
use App\Http\Controllers\EmissionStandardController;
use App\Http\Controllers\GroundWaterMonthController;
use App\Http\Controllers\AuthResumeTahunanController;
use App\Http\Controllers\EmissionStandard2Controller;
use App\Http\Controllers\PointIdDrinkWaterController;
use App\Http\Controllers\ResourceDataEntryController;
use App\Http\Controllers\ResourceMasterTTNController;
use App\Http\Controllers\ResourceWellLevelController;
use App\Http\Controllers\WastewaterPointiDController;
use App\Http\Controllers\EvaporationPointIdController;
use App\Http\Controllers\MarinesurfacewaterController;
use App\Http\Controllers\ResourceCodeSampleController;
use App\Http\Controllers\ResourceMasterGWGwController;
use App\Http\Controllers\ResumeBulananNoiseController;
use App\Http\Controllers\ResumeTahunanNoiseController;
use App\Http\Controllers\SoilQualityPointIDController;
use App\Http\Controllers\WastewaterStandardController;
use App\Http\Controllers\SoilQualityStandardController;
use App\Http\Controllers\SurfacewaterMonthlyController;
use App\Http\Controllers\ResourceCodeSampleDgController;
use App\Http\Controllers\ResourceCodeSampleGwController;
use App\Http\Controllers\StandardSurfacewaterController;
use App\Http\Controllers\QualityStandardMarineController;
use App\Http\Controllers\ResourceCodeSampleTTNController;
use App\Http\Controllers\AuthResumeMonthlyNoiseController;
use App\Http\Controllers\DischargeManualPointidController;
use App\Http\Controllers\GroundWaterMonthStandardController;
use App\Http\Controllers\DischargeManualQualityStandardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);
Route::get('/register', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);
//admin
Route::get('/', [DashboardController::class, 'index'])->middleware('auth');
Route::resource('/surfacewater/qualityperiode/codesample', ResourceCodeSampleController::class)->middleware('admin');
Route::resource('/surfacewater/standardtable', StandardSurfacewaterController::class)->middleware('auth');
Route::resource('/surfacewater/monthly', SurfacewaterMonthlyController::class)->middleware('auth');
Route::resource('/surfacewater/qualityperiode', ResourceDataEntryController::class)->middleware('auth');
Route::resource('/surfacewater/drinkwater/quantity', StdDrinkWaterController::class)->middleware('admin');
Route::resource('/surfacewater/drinkwater/pointid', PointIdDrinkWaterController::class)->middleware('admin');
Route::resource('/surfacewater/drinkwater', DrinkWaterController::class)->middleware('auth');
Route::resource('/surfacewater/marinesurfacewater/pointid', PointIdMarineController::class)->middleware('admin');
Route::resource('/surfacewater/marinesurfacewater/quality', QualityStandardMarineController::class)->middleware('admin');
Route::resource('/surfacewater/marinesurfacewater', MarinesurfacewaterController::class)->middleware('auth');
Route::resource('/groundwater/masterttn/codesamplettn', ResourceCodeSampleTTNController::class)->middleware('admin');
Route::resource('/groundwater/mastergw/codesamplegw', ResourceCodeSampleGwController::class)->middleware('admin');
Route::resource('/groundwater/standard', GroundWaterMonthStandardController::class)->middleware('admin');
Route::resource('/groundwater/monthly', GroundWaterMonthController::class)->middleware('admin');
Route::resource('/groundwater/mastergw', ResourceMasterGWGwController::class)->middleware('auth');
Route::resource('/groundwater/masterttn', ResourceMasterTTNController::class)->middleware('auth');
// Route::resource('/groundwater/standard', GwStandardController::class)->middleware('admin');
Route::resource('/groundwater/level', ResourceWellLevelController::class)->except('show', 'edit', 'delete')->middleware('auth');
Route::resource('/airquality/dustgauge/dust/codesampledg', ResourceCodeSampleDgController::class)->middleware('admin');
Route::resource('/airquality/dustgauge/dust', DustController::class)->middleware('auth');
Route::resource('/airquality/noisemeter/noise/codesamplenm', CodeSampleNMController::class)->middleware('admin');
Route::resource('/airquality/noisemeter/noise/locationnoise', LocationNoiseController::class)->middleware('admin');
Route::resource('/airquality/noisemeter/resumebulanan', ResumeBulananNoiseController::class)->middleware('auth');
Route::resource('/airquality/noisemeter/resumetahunan', ResumeTahunanNoiseController::class)->middleware('auth');
Route::resource('/airquality/noisemeter/noise', NoiseController::class)->middleware('auth');
Route::resource('/airquality/ambien/pointid', AmbienPointidController::class)->middleware('admin');
Route::resource('/airquality/ambien/standard', AmbienQualityStdController::class)->middleware('admin');
Route::resource('/airquality/ambien', AmbienController::class)->middleware('auth');
Route::resource('/airquality/emission/pointid', EmissionPointIdController::class)->middleware('admin');
Route::resource('/airquality/emission/standard', EmissionStandard2Controller::class)->middleware('admin');
Route::resource('/airquality/emission/standard2', EmissionStandardController::class)->middleware('admin');
Route::resource('/airquality/emission', EmissionController::class)->middleware('auth');
Route::resource('/airquality/emission2', Emission2Controller::class)->middleware('auth');
Route::resource('/monitoring/freshwater/biota', BiotaController::class)->middleware('admin');
Route::resource('/monitoring/location', LocationBiotaController::class)->middleware('admin');
Route::resource('/monitoring/freshwater/master', FreshWaterController::class)->middleware('auth');
Route::resource('/monitoring/marine', MarineController::class)->middleware('auth');
Route::resource('/blasting/pointid', PointIdBlastingController::class)->middleware('admin');
Route::resource('/blasting/tablestandard', StdBlastingTable::class)->middleware('admin');
Route::resource('/blasting', BlastingController::class)->middleware('auth');
Route::resource('/hydrometric/wlvp/qualitystandard', QualityStandardController::class)->middleware('admin');
Route::resource('/hydrometric/wlvp/point', HydroCodeController::class)->middleware('admin');
Route::resource('/hydrometric/wlvp', HydrometricController::class)->middleware('auth');
Route::resource('/hydrometric/dischargemanual/pointid', DischargeManualPointidController::class)->middleware('admin');
Route::resource('/hydrometric/dischargemanual/standard', DischargeManualQualityStandardController::class)->middleware('admin');
Route::resource('/hydrometric/dischargemanual', DischargeManualController::class)->middleware('auth');
Route::resource('/tailing/qualitystandard', TailingStandardController::class)->middleware('admin');
Route::resource('/tailing/codeid', TailingCodeIdController::class)->middleware('admin');
Route::resource('/tailing', TailingController::class)->middleware('auth');
Route::resource('/soilquality/soilqualitypointid',SoilQualityPointIDController::class)->middleware('admin');
Route::resource('/soilquality/soilqualitystandard',SoilQualityStandardController::class)->middleware('admin');
Route::resource('/soilquality',SoilQualityController::class)->middleware('auth');
Route::resource('/wastewater/wastewaterpointid',WastewaterPointiDController::class)->middleware('admin');
Route::resource('/wastewater/wastewaterstandard',WastewaterStandardController::class)->middleware('admin');
Route::resource('/wastewater',WastewaterController::class)->middleware('auth');
Route::resource('/weather/rainfall/rainfallpointid',RainfallPointIdController::class)->middleware('admin');
Route::resource('/weather/rainfall',RainfallController::class)->middleware('auth');
Route::resource('/weather/evaporation/evaporationpointid',EvaporationPointIdController::class)->middleware('admin');
Route::resource('/weather/evaporation',EvaporationController::class)->middleware('auth');
// export & import
Route::get('/exportdata', [ResourceDataEntryController::class, 'dataexport'])->middleware('admin');
Route::post('/importdata', [ResourceDataEntryController::class, 'dataimportexcel'])->middleware('admin');
Route::get('/exportmastergw', [ResourceMasterGWGwController::class, 'MasterExportGWExcel'])->middleware('admin');
Route::post('/importmastergw', [ResourceMasterGWGwController::class, 'MasterImportGWExcel'])->middleware('admin');
Route::get('/exportmasterttn', [ResourceMasterTTNController::class, 'MasterExportTTNExcel'])->middleware('admin');
Route::post('/importmasterttn', [ResourceMasterTTNController::class, 'MasterImportTTNExcel'])->middleware('admin');
Route::get('/exportcodesamplegw', [ResourceCodeSampleGwController::class, 'ExportCodeSampleGW'])->middleware('admin');
Route::post('/importcodesamplegw', [ResourceCodeSampleGwController::class, 'ImportCodeSampleGW'])->middleware('admin');
Route::get('/exportcodesamplettn', [ResourceCodeSampleTTNController::class, 'ExportCodeSampleTTN'])->middleware('admin');
Route::post('/importcodesamplettn', [ResourceCodeSampleTTNController::class, 'ImportCodeSampleTTN'])->middleware('admin');
Route::get('/exportcodesampledg', [ResourceCodeSampleDgController::class, 'ExportCodeSampleDG'])->middleware('admin');
Route::post('/importcodesampledg', [ResourceCodeSampleDgController::class, 'ImportCodeSampleDG'])->middleware('admin');
Route::get('/exportcodesamplesw', [ResourceCodeSampleController::class, 'ExportCodeSampleSW'])->middleware('admin');
Route::post('/importcodesamplesw', [ResourceCodeSampleController::class, 'ImportCodeSampleSW'])->middleware('admin');
Route::get('/export/codehydro', [HydroCodeController::class, 'ExportCodeHydro'])->middleware('admin');
Route::post('/import/codehydro', [HydroCodeController::class, 'ImportCodeHydro'])->middleware('admin');
Route::get('/export/standardhydro', [QualityStandardController::class, 'ExportWL'])->middleware('admin');
Route::post('/import/standardhydro', [QualityStandardController::class, 'ImportWL'])->middleware('admin');
Route::get('/export/hydrometric', [HydrometricController::class, 'ExportHydro'])->middleware('admin');
Route::post('/import/hydrometric', [HydrometricController::class, 'ImportHydro'])->middleware('admin');
Route::get('/export/drinkwater/pointid', [PointIdDrinkWaterController::class, 'ExportdrinkwaterPointId'])->middleware('admin');
Route::post('/import/drinkwater/pointid', [PointIdDrinkWaterController::class, 'ImportdrinkwaterPointId'])->middleware('admin');
Route::get('/export/marinesurfacewater/pointid', [PointIdMarineController::class, 'ExportPointIdMarine'])->middleware('admin');
Route::post('/import/marinesurfacewater/pointid', [PointIdMarineController::class, 'ImportPointIdMarine'])->middleware('admin');
Route::get('/export/marinesurfacewater/quality', [QualityStandardMarineController::class, 'ExportMarineSurfacewater'])->middleware('admin');
Route::post('/import/marinesurfacewater/quality', [QualityStandardMarineController::class, 'ImportQualityStandardMarine'])->middleware('admin');
Route::get('/export/marinesurfacewater', [MarinesurfacewaterController::class, 'ExportMarineSurfacewater'])->middleware('admin');
Route::post('/import/marinesurfacewater', [MarinesurfacewaterController::class, 'ImportMarineSurfacewater'])->middleware('admin');
Route::get('/export/drinkwater/std', [StdDrinkWaterController::class, 'ExportdrinkwaterStd'])->middleware('admin');
Route::post('/import/drinkwater/std', [StdDrinkWaterController::class, 'ImportdrinkwaterStd'])->middleware('admin');
Route::get('/export/drinkwater', [DrinkWaterController::class, 'Exportdrinkwater'])->middleware('admin');
Route::post('/import/drinkwater', [DrinkWaterController::class, 'Importdrinkwater'])->middleware('admin');
Route::get('/exportdatanoise', [NoiseController::class, 'ExportDataNoise'])->middleware('admin');
Route::post('/importdatanoise', [NoiseController::class, 'ImportDataNoise'])->middleware('admin');
Route::get('/exportlocation', [LocationNoiseController::class, 'ExportLocationNoise'])->middleware('admin');
Route::post('import/location/noise', [LocationNoiseController::class, 'ImportLocationNoise'])->middleware('admin');
Route::get('/exportbiota', [BiotaController::class, 'ExportBiota'])->middleware('admin');
Route::post('/importbiota', [BiotaController::class, 'ImportBiota'])->middleware('admin');
Route::get('/exportlocationbiota', [LocationBiotaController::class, 'ExportLocationBiota'])->middleware('admin');
Route::post('/importlocationbiota', [LocationBiotaController::class, 'ImportLocationBiota'])->middleware('admin');
Route::get('/exportmarine', [MarineController::class, 'ExportMarine'])->middleware('admin');
Route::post('/importmarine', [MarineController::class, 'ImportMarine'])->middleware('admin');
Route::get('/exportfreshwater', [FreshWaterController::class, 'ExportFreshwater'])->middleware('admin');
Route::post('/importfreshwater', [FreshWaterController::class, 'ImportFreshwater'])->middleware('admin');
Route::get('/export/blasting', [BlastingController::class, 'ExportBlasting'])->middleware('admin');
Route::post('/import/blasting', [BlastingController::class, 'ImportBlasting'])->middleware('admin');
Route::get('/export/dust', [DustController::class, 'ExportDust'])->middleware('admin');
Route::post('/import/dust', [DustController::class, 'ImportDust'])->middleware('admin');
Route::get('/export/codesamplenm', [CodeSampleNMController::class, 'ExportCodeSampleNM'])->middleware('admin');
Route::post('/import/codesamplenm', [CodeSampleNMController::class, 'ImportCodeSampleNM'])->middleware('admin');
Route::get('/export/blasting/pointid', [PointIdBlastingController::class, 'ExportPointId'])->middleware('admin');
Route::post('/import/blasting/pointid', [PointIdBlastingController::class, 'ImportPointId'])->middleware('admin');
Route::get('/export/blasting/standart', [StdBlastingTable::class, 'ExportStandardBlasting'])->middleware('admin');
Route::post('/import/blasting/standart', [StdBlastingTable::class, 'ImportStandardBlasting'])->middleware('admin');
Route::get('/export/groundwater/standart', [GwStandardController::class, 'ExportStandardGroundwater'])->middleware('admin');
Route::post('/import/groundwater/standart', [GwStandardController::class, 'ImportStandardGroundwater'])->middleware('admin');
Route::get('/export/tailing/pointid', [TailingCodeIdController::class, 'ExportPointID'])->middleware('admin');
Route::post('/import/tailing/pointid', [TailingCodeIdController::class, 'ImportPointID'])->middleware('admin');
Route::get('/export/tailing/standard', [TailingStandardController::class, 'ExportQualityStandardTailing'])->middleware('admin');
Route::post('/import/tailing/standard', [TailingStandardController::class, 'ImportQualityStandardTailing'])->middleware('admin');
Route::get('/export/tailing', [TailingController::class, 'ExportTailing'])->middleware('admin');
Route::post('/import/tailing', [TailingController::class, 'ImportTailing'])->middleware('admin');
Route::get('/export/dischargemanual/pointid', [DischargeManualPointidController::class, 'ExportDischargeManualPointId'])->middleware('admin');
Route::post('/import/dischargemanual/pointid', [DischargeManualPointidController::class, 'ImportDischargeManualPointId'])->middleware('admin');
Route::get('/export/dischargemanual/standard', [DischargeManualQualityStandardController::class, 'ExportDischargeManualStandard'])->middleware('admin');
Route::post('/import/dischargemanual/standard', [DischargeManualQualityStandardController::class, 'ImportDischargeManualStandard'])->middleware('admin');
Route::get('/export/dischargemanual', [DischargeManualController::class, 'ExportDischargeManual'])->middleware('admin');
Route::post('/import/dischargemanual', [DischargeManualController::class, 'ImportDischargeManual'])->middleware('admin');
Route::get('/export/ambien/standart', [AmbienQualityStdController::class, 'ExportAmbienStandard'])->middleware('admin');
Route::post('/import/ambien/standart', [AmbienQualityStdController::class, 'ImporttAmbienStandard'])->middleware('admin');
Route::get('/export/ambien/pointid', [AmbienPointidController::class, 'ExportAmbienPointId'])->middleware('admin');
Route::post('/import/ambien/pointid', [AmbienPointidController::class, 'ImportAmbienPointId'])->middleware('admin');
Route::get('/export/ambien', [AmbienController::class, 'ExportAmbien'])->middleware('admin');
Route::post('/import/ambien', [AmbienController::class, 'ImportAmbien'])->middleware('admin');
Route::get('/export/emission/pointid', [EmissionPointIdController::class, 'ExportEmissionPointId'])->middleware('admin');
Route::post('/import/emission/pointid', [EmissionPointIdController::class, 'ImportEmissionPointId'])->middleware('admin');
Route::get('/export/emission/standard', [EmissionStandard2Controller::class, 'ExportQualityStandard'])->middleware('admin');
Route::post('/import/emission/standard', [EmissionStandard2Controller::class, 'ImportQualityStandard'])->middleware('admin');
Route::get('/export/emission/standard2', [EmissionStandardController::class, 'ExportQualityStandard2'])->middleware('admin');
Route::post('/import/emission/standard2', [EmissionStandardController::class, 'ImportQualityStandard2'])->middleware('admin');
Route::get('/export/emission', [EmissionController::class, 'ExportEmission'])->middleware('admin');
Route::post('/import/emission ', [EmissionController::class, 'ImportEmission'])->middleware('admin');
Route::get('/export/emission2', [Emission2Controller::class, 'ExportEmission2'])->middleware('admin');
Route::post('/import/emission2 ', [Emission2Controller::class, 'ImportEmission2'])->middleware('admin');
Route::get('/export/soilquality/pointid', [SoilQualityPointIDController::class, 'ExportSoilQualityPointId'])->middleware('admin');
Route::post('/import/soilquality/pointid ', [SoilQualityPointIDController::class, 'ImportSoilQualityPointId'])->middleware('admin');
Route::get('/export/soilquality/standard', [SoilQualityStandardController::class, 'ExportSoilStandard'])->middleware('admin');
Route::post('/import/soilquality/standard ', [SoilQualityStandardController::class, 'ImportSoilStandard'])->middleware('admin');
Route::get('/export/soilquality', [SoilQualityController::class, 'ExportSoil'])->middleware('admin');
Route::post('/import/soilquality', [SoilQualityController::class, 'ImportSoil'])->middleware('admin');
Route::get('/export/wastewaterstandard', [WastewaterStandardController::class, 'ExportWasteWaterStandard'])->middleware('admin');
Route::post('/import/wastewaterstandard', [WastewaterStandardController::class, 'ImportWasteWaterStandard'])->middleware('admin');
Route::get('/export/wastewaterpointid', [WastewaterPointiDController::class, 'ExportWasteWaterPointId'])->middleware('admin');
Route::post('/import/wastewaterpointid', [WastewaterPointiDController::class, 'ImportWasteWaterPointId'])->middleware('admin');
Route::get('/export/rainfall', [RainfallController::class, 'ExportRainfall'])->middleware('admin');
Route::post('/import/rainfall', [RainfallController::class, 'ImportRainfall'])->middleware('admin');
Route::get('/export/rainfallpointid', [RainfallPointIdController::class, 'ExportRainfallPointId'])->middleware('admin');
Route::post('/import/rainfallpointid', [RainfallPointIdController::class, 'ImportRainfallPointId'])->middleware('admin');
Route::get('/export/evaporationpointid', [EvaporationPointIdController::class, 'ExportEvaporationPoinId'])->middleware('admin');
Route::post('/import/evaporationpointid', [EvaporationPointIdController::class, 'ImportEvaporationPoinId'])->middleware('admin');
Route::get('/export/evaporation', [EvaporationController::class, 'ExportEvaporation'])->middleware('admin');
Route::post('/import/evaporation', [EvaporationController::class, 'ImportEvaporation'])->middleware('admin');
Route::get('/export/wastewater', [WastewaterController::class, 'ExportWastewater'])->middleware('admin');
Route::post('/import/wastewater', [WastewaterController::class, 'ImportWastewater'])->middleware('admin');
Route::post('/import/noisebulanan', [ResumeBulananNoiseController::class, 'ImportResumeBulananNoise'])->middleware('admin');
Route::get('/export/groundwater/standard', [GroundWaterMonthStandardController::class, 'ExportStandardGroundwater'])->middleware('admin');
Route::post('/import/groundwater/standard', [GroundWaterMonthStandardController::class, 'ImportStandardGroundwater'])->middleware('admin');
Route::get('/export/groundwater/month', [GroundWaterMonthController::class, 'ExportMonthGroundwater'])->middleware('admin');
Route::post('/import/groundwater/month', [GroundWaterMonthController::class, 'ImportMonthGroundwater'])->middleware('admin');
Route::get('/export/surfacewater/standard', [StandardSurfacewaterController::class, 'ExportStandardSurfacewater'])->middleware('admin');
Route::post('/import/surfacewater/standard', [StandardSurfacewaterController::class, 'ImportStandardSurfacewater'])->middleware('admin');
Route::get('/export/surfacewater/monthly', [SurfacewaterMonthlyController::class, 'ExportMonthlySurfacewater'])->middleware('admin');
Route::post('/import/surfacewater/monthly', [SurfacewaterMonthlyController::class, 'ImportMonthlySurfacewater'])->middleware('admin');
