<?php

namespace App\Imports;

use App\Models\Wastewaterstandard;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Concerns\SkipsFailures;

class ImportWasteWaterStandard implements ToModel, WithValidation, WithHeadingRow
{
    use SkipsErrors, Importable, SkipsFailures;
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new Wastewaterstandard([
            "user_id" => $row["user_id"],
            "nama" => $row["nama"],
            "conductivity" => $row["conductivity"],
            "tds" => $row["tds"],
            "tss" => $row["tss"],
            "turbidity" => $row["turbidity"],
            "hardness" => $row["hardness"],
            "alkalinity_as_caco3" => $row["alkalinity_as_caco3"],
            "alkalinity_carbonate" => $row["alkalinity_carbonate"],
            "alkalinity_bicarbonate" => $row["alkalinity_bicarbonate"],
            "temperature" => $row["temperature"],
            "salinity" => $row["salinity"],
            "do" => $row["do"],
            "ph" => $row["ph"],
            "alkalinity_total" => $row["alkalinity_total"],
            "cl" => $row["cl"],
            "fluoride" => $row["fluoride"],
            "sulphate" => $row["sulphate"],
            "sulphite" => $row["sulphite"],
            "free_chlorine" => $row["free_chlorine"],
            "fcn" => $row["fcn"],
            "total_cyanide" => $row["total_cyanide"],
            "wad_cyanide" => $row["wad_cyanide"],
            "ammonia" => $row["ammonia"],
            "nitrate" => $row["nitrate"],
            "nitrite" => $row["nitrite"],
            "phosphate" => $row["phosphate"],
            "total_phosphate" => $row["total_phosphate"],
            "aluminium" => $row["aluminium"],
            "antimony" => $row["antimony"],
            "arsenic" => $row["arsenic"],
            "barium" => $row["barium"],
            "cadmium" => $row["cadmium"],
            "calcium" => $row["calcium"],
            "chromium" => $row["chromium"],
            "chromium_hexavalent" => $row["chromium_hexavalent"],
            "cobalt" => $row["cobalt"],
            "copper" => $row["copper"],
            "iron" => $row["iron"],
            "lead" => $row["lead"],
            "magnesium" => $row["magnesium"],
            "manganese" => $row["manganese"],
            "mercury" => $row["mercury"],
            "nickel" => $row["nickel"],
            "selenium" => $row["selenium"],
            "silver" => $row["silver"],
            "sodium" => $row["sodium"],
            "tin" => $row["tin"],
            "zinc" => $row["zinc"],
            "aluminium_t_ai" => $row["aluminium_t_ai"],
            "arsenic_t_as" => $row["arsenic_t_as"],
            "cadmium_t_cd" => $row["cadmium_t_cd"],
            "chromium_t" => $row["chromium_t"],
            "chromium_hexavalent_t" => $row["chromium_hexavalent_t"],
            "cobalt_t" => $row["cobalt_t"],
            "cooper" => $row["cooper"],
            "lead_t" => $row["lead_t"],
            "selenium_t" => $row["selenium_t"],
            "mercury_t" => $row["mercury_t"],
            "nickel_t" => $row["nickel_t"],
            "zinc_t" => $row["zinc_t"],
            "bod" => $row["bod"],
            "cod" => $row["cod"],
            "oil_and_grease" => $row["oil_and_grease"],
            "phenols" => $row["phenols"],
            "surfactant" => $row["surfactant"],
            "total_pcb" => $row["total_pcb"],
            "a_o_x" => $row["a_o_x"],
            "pcdfs" => $row["pcdfs"],
            "pcdds" => $row["pcdds"],
            "fecal_coliform" => $row["fecal_coliform"],
            "e_coli" => $row["e_coli"],
            "total_coliform_bacteria" => $row["total_coliform_bacteria"],

        ]);
    }
    public function rules(): array
    {
        return[
            'user_id'=>'required',
            'nama' => 'required',
            'conductivity' => 'required',
            'tds' => 'required',
            'tss' => 'required',
            'turbidity' => 'required',
            'hardness' => 'required',
            'alkalinity_as_caco3' => 'required',
            'alkalinity_carbonate' => 'required',
            'alkalinity_bicarbonate' => 'required',
            'temperature' => 'required',
            'salinity' => 'required',
            'do' => 'required',
            'ph' => 'required',
            'alkalinity_total' => 'required',
            'cl' => 'required',
            'fluoride' => 'required',
            'sulphate' => 'required',
            'sulphite' => 'required',
            'free_chlorine' => 'required',
            'fcn' => 'required',
            'total_cyanide' => 'required',
            'wad_cyanide' => 'required',
            'ammonia' => 'required',
            'nitrate' => 'required',
            'nitrite' => 'required',
            'phosphate' => 'required',
            'total_phosphate' => 'required',
            'aluminium' => 'required',
            'antimony' => 'required',
            'arsenic' => 'required',
            'barium' => 'required',
            'cadmium' => 'required',
            'calcium' => 'required',
            'chromium' => 'required',
            'chromium_hexavalent' => 'required',
            'cobalt' => 'required',
            'copper' => 'required',
            'iron' => 'required',
            'lead' => 'required',
            'magnesium' => 'required',
            'manganese' => 'required',
            'mercury' => 'required',
            'nickel' => 'required',
            'selenium' => 'required',
            'silver' => 'required',
            'sodium' => 'required',
            'tin' => 'required',
            'zinc' => 'required',
            'aluminium_t_ai' => 'required',
            'arsenic_t_as' => 'required',
            'cadmium_t_cd' => 'required',
            'chromium_t' => 'required',
            'chromium_hexavalent_t' => 'required',
            'cobalt_t' => 'required',
            'cooper' => 'required',
            'lead_t' => 'required',
            'selenium_t' => 'required',
            'mercury_t' => 'required',
            'nickel_t' => 'required',
            'zinc_t' => 'required',
            'bod' => 'required',
            'cod' => 'required',
            'oil_and_grease' => 'required',
            'phenols' => 'required',
            'surfactant' => 'required',
            'total_pcb' => 'required',
            'a_o_x' => 'required',
            'pcdfs' => 'required',
            'pcdds' => 'required',
            'fecal_coliform' => 'required',
            'e_coli' => 'required',
            'total_coliform_bacteria' => 'required',
        ];
    }
}
