<?php

namespace App\Imports;

use App\Models\Tailing;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class ImportTailing implements ToModel, WithValidation, WithHeadingRow
{
    use SkipsErrors, Importable, SkipsFailures;
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new Tailing([
            "point_id" => $row["point_id"],
            "user_id" => $row["user_id"],
            "date" => $row["date"],
            "antimony" => $row["antimony"],
            "arsenic" => $row["arsenic"],
            "barium" => $row["barium"],
            "beryllium" => $row["beryllium"],
            "boron" => $row["boron"],
            "cadmium" => $row["cadmium"],
            "hexavalent" => $row["hexavalent"],
            "chromium_cr" => $row["chromium_cr"],
            "copper" => $row["copper"],
            "iodide" => $row["iodide"],
            "lead" => $row["lead"],
            "mercury" => $row["mercury"],
            "molybdenum" => $row["molybdenum"],
            "nickel" => $row["nickel"],
            "selenium" => $row["selenium"],
            "silver" => $row["silver"],
            "tributyl" => $row["tributyl"],
            "zinc_zn" => $row["zinc_zn"],
            "chloride_cl" => $row["chloride_cl"],
            "free_cyanide" => $row["free_cyanide"],
            "total_cyanide" => $row["total_cyanide"],
            "fluoride" => $row["fluoride"],
            "nitrite_no2" => $row["nitrite_no2"],
            "nitrate" => $row["nitrate"],
            "aldrin" => $row["aldrin"],
            "dieldrin" => $row["dieldrin"],
            "benzene" => $row["benzene"],
            "benzo_a_pyrene" => $row["benzo_a_pyrene"],
            "tetrachloride" => $row["tetrachloride"],
            "chlordane" => $row["chlordane"],
            "chlorobenzene" => $row["chlorobenzene"],
            "chlorophenol2" => $row["chlorophenol2"],
            "chloroform" => $row["chloroform"],
            "o_cresol" => $row["o_cresol"],
            "m_cresol" => $row["m_cresol"],
            "p_cresol" => $row["p_cresol"],
            "total_cresol" => $row["total_cresol"],
            "ethylhexylphthalate" => $row["ethylhexylphthalate"],
            "d" => $row["d"],
            "dichlorobenzene2" => $row["dichlorobenzene2"],
            "dichlorobenzene4" => $row["dichlorobenzene4"],
            "dichloroethane1" => $row["dichloroethane1"],
            "dichloroethylene" => $row["dichloroethylene"],
            "dichloroethene2" => $row["dichloroethene2"],
            "dichloroethene3" => $row["dichloroethene3"],
            "dichloromethane" => $row["dichloromethane"],
            "dichlorophenol" => $row["dichlorophenol"],
            "dinitrotoluene" => $row["dinitrotoluene"],
            "ethyl_benzene" => $row["ethyl_benzene"],
            "thylenediaminetetraacetic" => $row["thylenediaminetetraacetic"],
            "formaldehyde" => $row["formaldehyde"],
            "hexachloro" => $row["hexachloro"],
            "endrin" => $row["endrin"],
            "heptachlor" => $row["heptachlor"],
            "hexachlorobenzene" => $row["hexachlorobenzene"],
            "hexachlorobutadiene" => $row["hexachlorobutadiene"],
            "hexachloroethane" => $row["hexachloroethane"],
            "total_phenols" => $row["total_phenols"],
            "lindane" => $row["lindane"],
            "methoxychlor1" => $row["methoxychlor1"],
            "ketone" => $row["ketone"],
            "parathion1" => $row["parathion1"],
            "nitrobenzene" => $row["nitrobenzene"],
            "styrene" => $row["styrene"],
            "tetrachloroethane1" => $row["tetrachloroethane1"],
            "tetrachloroethane2" => $row["tetrachloroethane2"],
            "nitriloacetic" => $row["nitriloacetic"],
            "pentachlorophenol" => $row["pentachlorophenol"],
            "pyridine" => $row["pyridine"],
            "toxaphene1" => $row["toxaphene1"],
            "parathion" => $row["parathion"],
            "total_chlor" => $row["total_chlor"],
            "tetrachloroethene" => $row["tetrachloroethene"],
            "toluene" => $row["toluene"],
            "trichlorobenzene" => $row["trichlorobenzene"],
            "methoxychlor2" => $row["methoxychlor2"],
            "trichloroethane1" => $row["trichloroethane1"],
            "trichloroethene2" => $row["trichloroethene2"],
            "toxaphene2" => $row["toxaphene2"],
            "trichloroethylene" => $row["trichloroethylene"],
            "trihalomethanes" => $row["trihalomethanes"],
            "trichlorophenol5" => $row["trichlorophenol5"],
            "trichlorophenol6" => $row["trichlorophenol6"],
            "tp_silvex" => $row["tp_silvex"],
            "vinyl_chloride" => $row["vinyl_chloride"],
            "xylenes_total" => $row["xylenes_total"],
            "ddt_ddd_dde" => $row["ddt_ddd_dde"],
            "dichlorophenoxyacetic" => $row["dichlorophenoxyacetic"],

        ]);
    }
    public function rules(): array
    {
        return [
            'point_id'=>'required',
            'user_id'=>'required',
            'date' => 'required',
            'antimony' => 'required',
            'arsenic' => 'required',
            'barium' => 'required',
            'beryllium' => 'required',
            'boron' => 'required',
            'cadmium' => 'required',
            'hexavalent' => 'required',
            'chromium_cr' => 'required',
            'copper' => 'required',
            'iodide' => 'required',
            'lead' => 'required',
            'mercury' => 'required',
            'molybdenum' => 'required',
            'nickel' => 'required',
            'selenium' => 'required',
            'silver' => 'required',
            'tributyl' => 'required',
            'zinc_zn' => 'required',
            'chloride_cl' => 'required',
            'free_cyanide' => 'required',
            'total_cyanide' => 'required',
            'fluoride' => 'required',
            'nitrite_no2' => 'required',
            'nitrate' => 'required',
            'aldrin' => 'required',
            'dieldrin' => 'required',
            'benzene' => 'required',
            'benzo_a_pyrene' => 'required',
            'tetrachloride' => 'required',
            'chlordane' => 'required',
            'chlorobenzene' => 'required',
            'chlorophenol2' => 'required',
            'chloroform' => 'required',
            'o_cresol' => 'required',
            'm_cresol' => 'required',
            'p_cresol' => 'required',
            'total_cresol' => 'required',
            'ethylhexylphthalate' => 'required',
            'd' => 'required',
            'dichlorobenzene2' => 'required',
            'dichlorobenzene4' => 'required',
            'dichloroethane1' => 'required',
            'dichloroethylene' => 'required',
            'dichloroethene2' => 'required',
            'dichloroethene3' => 'required',
            'dichloromethane' => 'required',
            'dichlorophenol' => 'required',
            'dinitrotoluene' => 'required',
            'ethyl_benzene' => 'required',
            'thylenediaminetetraacetic' => 'required',
            'formaldehyde' => 'required',
            'hexachloro' => 'required',
            'endrin' => 'required',
            'heptachlor' => 'required',
            'hexachlorobenzene' => 'required',
            'hexachlorobutadiene' => 'required',
            'hexachloroethane' => 'required',
            'total_phenols' => 'required',
            'lindane' => 'required',
            'methoxychlor1' => 'required',
            'ketone' => 'required',
            'parathion1' => 'required',
            'nitrobenzene' => 'required',
            'styrene' => 'required',
            'tetrachloroethane1' => 'required',
            'tetrachloroethane2' => 'required',
            'nitriloacetic' => 'required',
            'pentachlorophenol' => 'required',
            'pyridine' => 'required',
            'toxaphene1' => 'required',
            'parathion' => 'required',
            'total_chlor' => 'required',
            'tetrachloroethene' => 'required',
            'toluene' => 'required',
            'trichlorobenzene' => 'required',
            'methoxychlor2' => 'required',
            'trichloroethane1' => 'required',
            'trichloroethene2' => 'required',
            'toxaphene2' => 'required',
            'trichloroethylene' => 'required',
            'trihalomethanes' => 'required',
            'trichlorophenol5' => 'required',
            'trichlorophenol6' => 'required',
            'tp_silvex' => 'required',
            'vinyl_chloride' => 'required',
            'xylenes_total' => 'required',
            'ddt_ddd_dde' => 'required',
            'dichlorophenoxyacetic' => 'required',
        ];
    }
}
