<?php

namespace App\Imports;

use Maatwebsite\Excel\Concerns\ToModel;
use App\Models\GroundWaterMonthStandard;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class ImportStandardGroundwater implements ToModel, WithValidation, WithHeadingRow
{
    use SkipsErrors, Importable, SkipsFailures;
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new GroundWaterMonthStandard([
            "user_id" => $row["user_id"],
            "nama" => $row["nama"],
            "conductivity" => $row["conductivity"],
            "total_dissolved_solids_tds" => $row["total_dissolved_solids_tds"],
            "total_suspended_solids_tss" => $row["total_suspended_solids_tss"],
            "turbidity" => $row["turbidity"],
            "hardness" => $row["hardness"],
            "alkalinity" => $row["alkalinity"],
            "temperature" => $row["temperature"],
            "salinity" => $row["salinity"],
            "dissolved_oxygen_do" => $row["dissolved_oxygen_do"],
            "colour" => $row["colour"],
            "odour" => $row["odour"],
            "taste" => $row["taste"],
            "ph" => $row["ph"],
            "chloride_cl" => $row["chloride_cl"],
            "fluoride_f" => $row["fluoride_f"],
            "residual_chlorine" => $row["residual_chlorine"],
            "sulphate_so4" => $row["sulphate_so4"],
            "sulphite_h2s" => $row["sulphite_h2s"],
            "free_cyanide_fcn" => $row["free_cyanide_fcn"],
            "total_cyanide_cn_tot" => $row["total_cyanide_cn_tot"],
            "wad_cyanide_cn_wad" => $row["wad_cyanide_cn_wad"],
            "ammonium_nh4" => $row["ammonium_nh4"],
            "ammonia_n_nh3" => $row["ammonia_n_nh3"],
            "nitrate_no3" => $row["nitrate_no3"],
            "nitrite_no2" => $row["nitrite_no2"],
            "phosphate_po4" => $row["phosphate_po4"],
            "aluminium_al" => $row["aluminium_al"],
            "antimony_sb" => $row["antimony_sb"],
            "arsenic_as" => $row["arsenic_as"],
            "barium_ba" => $row["barium_ba"],
            "cadmium_cd" => $row["cadmium_cd"],
            "chromium_cr" => $row["chromium_cr"],
            "chromium_hexavalent_cr6" => $row["chromium_hexavalent_cr6"],
            "cobalt_co" => $row["cobalt_co"],
            "copper_cu" => $row["copper_cu"],
            "iron_fe" => $row["iron_fe"],
            "manganese_mn" => $row["manganese_mn"],
            "lead_pb" => $row["lead_pb"],
            "mercury_hg" => $row["mercury_hg"],
            "nickel_ni" => $row["nickel_ni"],
            "selenium_se" => $row["selenium_se"],
            "silver_ag" => $row["silver_ag"],
            "zinc_zn" => $row["zinc_zn"],
            "aluminium_t_al" => $row["aluminium_t_al"],
            "arsenic_t_as" => $row["arsenic_t_as"],
            "cadmium_t_cd" => $row["cadmium_t_cd"],
            "chromium_hexavalent_t_cr6" => $row["chromium_hexavalent_t_cr6"],
            "chromium_t_cr" => $row["chromium_t_cr"],
            "cobalt_t_co" => $row["cobalt_t_co"],
            "copper_t_cu" => $row["copper_t_cu"],
            "lead_t_pb" => $row["lead_t_pb"],
            "selenium_t_se" => $row["selenium_t_se"],
            "mercury_t_hg" => $row["mercury_t_hg"],
            "nickel_t_ni" => $row["nickel_t_ni"],
            "zinc_t_zn" => $row["zinc_t_zn"],
            "bod" => $row["bod"],
            "cod" => $row["cod"],
            "oil_and_grease" => $row["oil_and_grease"],
            "phenols" => $row["phenols"],
            "permanganate_number_as_kmno4" => $row["permanganate_number_as_kmno4"],
            "surfactant_mbas" => $row["surfactant_mbas"],
            "benzene" => $row["benzene"],
            "chloroform" => $row["chloroform"],
            "2_4_6_trichloropenol" => $row["2_4_6_trichloropenol"],
            "2_4_d" => $row["2_4_d"],
            "pentachlorophenol" => $row["pentachlorophenol"],
            "total_pesticides" => $row["total_pesticides"],
            "chlordane_total_isomer" => $row["chlordane_total_isomer"],
            "dieldrin" => $row["dieldrin"],
            "aldrin" => $row["aldrin"],
            "fecal_coliform" => $row["fecal_coliform"],
            "e_coli" => $row["e_coli"],
            "total_coliform_bacteria" => $row["total_coliform_bacteria"]

        ]);
    }
    public function rules(): array
    {
        return [
            "user_id" => 'required',
            "nama" => 'required',
            "conductivity" => 'required',
            "total_dissolved_solids_tds" => 'required',
            "total_suspended_solids_tss" => 'required',
            "turbidity" => 'required',
            "hardness" => 'required',
            "alkalinity" => 'required',
            "temperature" => 'required',
            "salinity" => 'required',
            "dissolved_oxygen_do" => 'required',
            "colour" => 'required',
            "odour" => 'required',
            "taste" => 'required',
            "ph" => 'required',
            "chloride_cl" => 'required',
            "fluoride_f" => 'required',
            "residual_chlorine" => 'required',
            "sulphate_so4" => 'required',
            "sulphite_h2s" => 'required',
            "free_cyanide_fcn" => 'required',
            "total_cyanide_cn_tot" => 'required',
            "wad_cyanide_cn_wad" => 'required',
            "ammonium_nh4" => 'required',
            "ammonia_n_nh3" => 'required',
            "nitrate_no3" => 'required',
            "nitrite_no2" => 'required',
            "phosphate_po4" => 'required',
            "aluminium_al" => 'required',
            "antimony_sb" => 'required',
            "arsenic_as" => 'required',
            "barium_ba" => 'required',
            "cadmium_cd" => 'required',
            "chromium_cr" => 'required',
            "chromium_hexavalent_cr6" => 'required',
            "cobalt_co" => 'required',
            "copper_cu" => 'required',
            "iron_fe" => 'required',
            "manganese_mn" => 'required',
            "lead_pb" => 'required',
            "mercury_hg" => 'required',
            "nickel_ni" => 'required',
            "selenium_se" => 'required',
            "silver_ag" => 'required',
            "zinc_zn" => 'required',
            "aluminium_t_al" => 'required',
            "arsenic_t_as" => 'required',
            "cadmium_t_cd" => 'required',
            "chromium_hexavalent_t_cr6" => 'required',
            "chromium_t_cr" => 'required',
            "cobalt_t_co" => 'required',
            "copper_t_cu" => 'required',
            "lead_t_pb" => 'required',
            "selenium_t_se" => 'required',
            "mercury_t_hg" => 'required',
            "nickel_t_ni" => 'required',
            "zinc_t_zn" => 'required',
            "bod" => 'required',
            "cod" => 'required',
            "oil_and_grease" => 'required',
            "phenols" => 'required',
            "permanganate_number_as_kmno4" => 'required',
            "surfactant_mbas" => 'required',
            "benzene" => 'required',
            "chloroform" => 'required',
            "2_4_6_trichloropenol" => 'required',
            "2_4_d" => 'required',
            "pentachlorophenol" => 'required',
            "total_pesticides" => 'required',
            "chlordane_total_isomer" => 'required',
            "dieldrin" => 'required',
            "aldrin" => 'required',
            "fecal_coliform" => 'required',
            "e_coli" => 'required',
            "total_coliform_bacteria" => 'required',

        ];
    }
}
