<?php

namespace App\Imports;

use App\Models\Wastewater;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class ImportWastewater implements ToModel, WithValidation, WithHeadingRow
{
    use SkipsErrors, Importable, SkipsFailures;
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new Wastewater([
            "user_id" => $row["user_id"],
            "point_id" => $row["point_id"],
            "standard_id" => $row["standard_id"],
            "date" => $row["date"],
            "conductivity" => $row["conductivity"],
            "totaldissolvedsolids_tds" => $row["totaldissolvedsolids_tds"],
            "totalsuspendedsolids_tss" => $row["totalsuspendedsolids_tss"],
            "turbidity" => $row["turbidity"],
            "hardness" => $row["hardness"],
            "alkalinity_ascaco3" => $row["alkalinity_ascaco3"],
            "alkalinitycarbonate" => $row["alkalinitycarbonate"],
            "alkalinitybicarbonate" => $row["alkalinitybicarbonate"],
            "temperature" => $row["temperature"],
            "salinity" => $row["salinity"],
            "dissolvedoxygen_do" => $row["dissolvedoxygen_do"],
            "ph" => $row["ph"],
            "alkalinitytotal" => $row["alkalinitytotal"],
            "chloride_cl" => $row["chloride_cl"],
            "fluoride_f" => $row["fluoride_f"],
            "sulphate_so4" => $row["sulphate_so4"],
            "sulphite_h2s" => $row["sulphite_h2s"],
            "freechlorine_cl2" => $row["freechlorine_cl2"],
            "freecyanide_fcn" => $row["freecyanide_fcn"],
            "totalcyanide_cntot" => $row["totalcyanide_cntot"],
            "wadcyanide_cnwad" => $row["wadcyanide_cnwad"],
            "ammonia_nh4" => $row["ammonia_nh4"],
            "ammonium_n_nh3" => $row["ammonium_n_nh3"],
            "nitrate_no3" => $row["nitrate_no3"],
            "nitrite_no2" => $row["nitrite_no2"],
            "phosphate_po4" => $row["phosphate_po4"],
            "totalphosphate_ppo4" => $row["totalphosphate_ppo4"],
            "aluminium_al" => $row["aluminium_al"],
            "antimony_sb" => $row["antimony_sb"],
            "arsenic_as" => $row["arsenic_as"],
            "barium_ba" => $row["barium_ba"],
            "cadmium_cd" => $row["cadmium_cd"],
            "calcium_ca" => $row["calcium_ca"],
            "chromium_cr" => $row["chromium_cr"],
            "chromiumhexavalent_cr6" => $row["chromiumhexavalent_cr6"],
            "cobalt_co" => $row["cobalt_co"],
            "copper_cu" => $row["copper_cu"],
            "iron_fe" => $row["iron_fe"],
            "lead_pb" => $row["lead_pb"],
            "magnesium_mg" => $row["magnesium_mg"],
            "manganese_mn" => $row["manganese_mn"],
            "mercury_hg" => $row["mercury_hg"],
            "nickel_ni" => $row["nickel_ni"],
            "selenium_se" => $row["selenium_se"],
            "silver_ag" => $row["silver_ag"],
            "sodium_na" => $row["sodium_na"],
            "tin_sn" => $row["tin_sn"],
            "zinc_zn" => $row["zinc_zn"],
            "aluminium_tal" => $row["aluminium_tal"],
            "arsenic_tas" => $row["arsenic_tas"],
            "cadmium_tcd" => $row["cadmium_tcd"],
            "chromiumhexavalent_tcr6" => $row["chromiumhexavalent_tcr6"],
            "chromium_tcr" => $row["chromium_tcr"],
            "cobalt_tco" => $row["cobalt_tco"],
            "copper_tco" => $row["copper_tco"],
            "lead_tpb" => $row["lead_tpb"],
            "selenium_tse" => $row["selenium_tse"],
            "mercury_thg" => $row["mercury_thg"],
            "nickel_tni" => $row["nickel_tni"],
            "zinc_tzn" => $row["zinc_tzn"],
            "bod" => $row["bod"],
            "cod" => $row["cod"],
            "oilandgrease" => $row["oilandgrease"],
            "totalphenols" => $row["totalphenols"],
            "surfactant_mbas" => $row["surfactant_mbas"],
            "totalpcb" => $row["totalpcb"],
            "aox" => $row["aox"],
            "pcdfs" => $row["pcdfs"],
            "pcdds" => $row["pcdds"],
            "fecalcoliform" => $row["fecalcoliform"],
            "ecoli" => $row["ecoli"],
            "totalcoliformbacteria" => $row["totalcoliformbacteria"],

        ]);
    }
    public function rules(): array
    {
        return[
            'user_id'=>'required',
            'point_id' => 'required',
            'standard_id' => 'required',
            'date' => 'required',
            "conductivity"  => 'required',
            "totaldissolvedsolids_tds"  => 'required',
            "totalsuspendedsolids_tss"  => 'required',
            "turbidity"  => 'required',
            "hardness"  => 'required',
            "alkalinity_ascaco3"  => 'required',
            "alkalinitycarbonate"  => 'required',
            "alkalinitybicarbonate"  => 'required',
            "temperature"  => 'required',
            "salinity"  => 'required',
            "dissolvedoxygen_do"  => 'required',
            "ph"  => 'required',
            "alkalinitytotal"  => 'required',
            "chloride_cl"  => 'required',
            "fluoride_f"  => 'required',
            "sulphate_so4"  => 'required',
            "sulphite_h2s"  => 'required',
            "freechlorine_cl2"  => 'required',
            "freecyanide_fcn"  => 'required',
            "totalcyanide_cntot"  => 'required',
            "wadcyanide_cnwad"  => 'required',
            "ammonia_nh4"  => 'required',
            "ammonium_n_nh3"  => 'required',
            "nitrate_no3"  => 'required',
            "nitrite_no2"  => 'required',
            "phosphate_po4"  => 'required',
            "totalphosphate_ppo4"  => 'required',
            "aluminium_al"  => 'required',
            "antimony_sb"  => 'required',
            "arsenic_as"  => 'required',
            "barium_ba"  => 'required',
            "cadmium_cd"  => 'required',
            "calcium_ca"  => 'required',
            "chromium_cr"  => 'required',
            "chromiumhexavalent_cr6"  => 'required',
            "cobalt_co"  => 'required',
            "copper_cu"  => 'required',
            "iron_fe"  => 'required',
            "lead_pb"  => 'required',
            "magnesium_mg"  => 'required',
            "manganese_mn"  => 'required',
            "mercury_hg"  => 'required',
            "nickel_ni"  => 'required',
            "selenium_se"  => 'required',
            "silver_ag"  => 'required',
            "sodium_na"  => 'required',
            "tin_sn"  => 'required',
            "zinc_zn"  => 'required',
            "aluminium_tal"  => 'required',
            "arsenic_tas"  => 'required',
            "cadmium_tcd"  => 'required',
            "chromiumhexavalent_tcr6"  => 'required',
            "chromium_tcr"  => 'required',
            "cobalt_tco"  => 'required',
            "copper_tco"  => 'required',
            "lead_tpb"  => 'required',
            "selenium_tse"  => 'required',
            "mercury_thg"  => 'required',
            "nickel_tni"  => 'required',
            "zinc_tzn"  => 'required',
            "bod"  => 'required',
            "cod"  => 'required',
            "oilandgrease"  => 'required',
            "totalphenols"  => 'required',
            "surfactant_mbas"  => 'required',
            "totalpcb"  => 'required',
            "aox"  => 'required',
            "pcdfs"  => 'required',
            "pcdds"  => 'required',
            "fecalcoliform"  => 'required',
            "ecoli"  => 'required',
            "totalcoliformbacteria"  => 'required',
        ];
    }
}
