<?php

namespace App\Imports;

use App\Models\SurfacewaterMonthly;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class MonthlyReportImport implements ToModel, WithValidation, WithHeadingRow
{
    use SkipsErrors, Importable, SkipsFailures;
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new SurfacewaterMonthly([
            'codesample_id' => $row['codesample_id'],
            'standard_id' => $row['standard_id'],
            'date' => $row['date'],
            'conductivity' => $row['conductivity'],
            'total_dissolved_solids_tds' => $row['total_dissolved_solids_tds'],
            'total_suspended_solids_tss' => $row['total_suspended_solids_tss'],
            'turbidity' => $row['turbidity'],
            'hardness' => $row['hardness'],
            'temperature' => $row['temperature'],
            'colour' => $row['colour'],
            'salinity' => $row['salinity'],
            'alkalinity_as_caco3' => $row['alkalinity_as_caco3'],
            'dissolved_oxygen_do' => $row['dissolved_oxygen_do'],
            'alkalinity_total' => $row['alkalinity_total'],
            'alkalinitycarbonate' => $row['alkalinitycarbonate'],
            'alkalinitybicarbonate' => $row['alkalinitybicarbonate'],
            'ph' => $row['ph'],
            'chloride_cl' => $row['chloride_cl'],
            'free_chlorine' => $row['free_chlorine'],
            'fluoride_f' => $row['fluoride_f'],
            'sulphate_so4' => $row['sulphate_so4'],
            'sulphite_h2s' => $row['sulphite_h2s'],
            'free_cyanide_fcn' => $row['free_cyanide_fcn'],
            'total_cyanide_cn_tot' => $row['total_cyanide_cn_tot'],
            'wad_cyanide_cn_wad' => $row['wad_cyanide_cn_wad'],
            'ammonium_nh4' => $row['ammonium_nh4'],
            'ammonia_nnh3' => $row['ammonia_nnh3'],
            'nitrate_no3' => $row['nitrate_no3'],
            'nitrite_no2' => $row['nitrite_no2'],
            'phosphate_po4' => $row['phosphate_po4'],
            'total_nitrogen' => $row['total_nitrogen'],
            'aluminium_al' => $row['aluminium_al'],
            'antimony_sb' => $row['antimony_sb'],
            'arsenic_as' => $row['arsenic_as'],
            'barium_ba' => $row['barium_ba'],
            'boron_b' => $row['boron_b'],
            'calcium_ca' => $row['calcium_ca'],
            'cadmium_cd' => $row['cadmium_cd'],
            'chromium_cr' => $row['chromium_cr'],
            'chromium_hexavalent_cr6' => $row['chromium_hexavalent_cr6'],
            'cobalt_co' => $row['cobalt_co'],
            'copper_cu' => $row['copper_cu'],
            'iron_fe' => $row['iron_fe'],
            'lead_pb' => $row['lead_pb'],
            'magnesium_mg' => $row['magnesium_mg'],
            'manganese_mn' => $row['manganese_mn'],
            'mercury_hg' => $row['mercury_hg'],
            'nickel_ni' => $row['nickel_ni'],
            'selenium_se' => $row['selenium_se'],
            'silver_ag' => $row['silver_ag'],
            'sodium_na' => $row['sodium_na'],
            'zinc_zn' => $row['zinc_zn'],
            'aluminium_tal' => $row['aluminium_tal'],
            'arsenic_tas' => $row['arsenic_tas'],
            'cadmium_tcd' => $row['cadmium_tcd'],
            'chromium_hexavalent_tcr6' => $row['chromium_hexavalent_tcr6'],
            'chromium_tcr' => $row['chromium_tcr'],
            'cobalt_tco' => $row['cobalt_tco'],
            'copper_tcu' => $row['copper_tcu'],
            'iron_tfe' => $row['iron_tfe'],
            'lead_tpb' => $row['lead_tpb'],
            'selenium_tse' => $row['selenium_tse'],
            'mercury_thg' => $row['mercury_thg'],
            'nickel_tni' => $row['nickel_tni'],
            'zinc_tzn' => $row['zinc_tzn'],
            'bod' => $row['bod'],
            'cod' => $row['cod'],
            'oil_and_grease' => $row['oil_and_grease'],
            'phenols' => $row['phenols'],
            'surfactant_mbas' => $row['surfactant_mbas'],
            'benzene_hexa_chloride_bhc' => $row['benzene_hexa_chloride_bhc'],
            'endrin' => $row['endrin'],
            'dichloro_diphenyl_trichloroethane_ddt' => $row['dichloro_diphenyl_trichloroethane_ddt'],
            'fecal_coliform' => $row['fecal_coliform'],
            'e_coli' => $row['e_coli'],
            'total_coliform_bacteria' => $row['total_coliform_bacteria'],
        ]);
    }
    public function rules(): array
    {
        return [
            'codesample_id' => 'required',
            'standard_id' => 'required',
            'date' => 'required',
            'conductivity' => 'required',
            'total_dissolved_solids_tds' => 'required',
            'total_suspended_solids_tss' => 'required',
            'turbidity' => 'required',
            'hardness' => 'required',
            'temperature' => 'required',
            'colour' => 'required',
            'salinity' => 'required',
            'alkalinity_as_caco3' => 'required',
            'dissolved_oxygen_do' => 'required',
            'alkalinity_total' => 'required',
            'alkalinitycarbonate' => 'required',
            'alkalinitybicarbonate' => 'required',
            'ph' => 'required',
            'chloride_cl' => 'required',
            'free_chlorine' => 'required',
            'fluoride_f' => 'required',
            'sulphate_so4' => 'required',
            'sulphite_h2s' => 'required',
            'free_cyanide_fcn' => 'required',
            'total_cyanide_cn_tot' => 'required',
            'wad_cyanide_cn_wad' => 'required',
            'ammonium_nh4' => 'required',
            'ammonia_nnh3' => 'required',
            'nitrate_no3' => 'required',
            'nitrite_no2' => 'required',
            'phosphate_po4' => 'required',
            'total_nitrogen' => 'required',
            'aluminium_al' => 'required',
            'antimony_sb' => 'required',
            'arsenic_as' => 'required',
            'barium_ba' => 'required',
            'boron_b' => 'required',
            'calcium_ca' => 'required',
            'cadmium_cd' => 'required',
            'chromium_cr' => 'required',
            'chromium_hexavalent_cr6' => 'required',
            'cobalt_co' => 'required',
            'copper_cu' => 'required',
            'iron_fe' => 'required',
            'lead_pb' => 'required',
            'magnesium_mg' => 'required',
            'manganese_mn' => 'required',
            'mercury_hg' => 'required',
            'nickel_ni' => 'required',
            'selenium_se' => 'required',
            'silver_ag' => 'required',
            'sodium_na' => 'required',
            'zinc_zn' => 'required',
            'aluminium_tal' => 'required',
            'arsenic_tas' => 'required',
            'cadmium_tcd' => 'required',
            'chromium_hexavalent_tcr6' => 'required',
            'chromium_tcr' => 'required',
            'cobalt_tco' => 'required',
            'copper_tcu' => 'required',
            'iron_tfe' => 'required',
            'lead_tpb' => 'required',
            'selenium_tse' => 'required',
            'mercury_thg' => 'required',
            'nickel_tni' => 'required',
            'zinc_tzn' => 'required',
            'bod' => 'required',
            'cod' => 'required',
            'oil_and_grease' => 'required',
            'phenols' => 'required',
            'surfactant_mbas' => 'required',
            'benzene_hexa_chloride_bhc' => 'required',
            'endrin' => 'required',
            'dichloro_diphenyl_trichloroethane_ddt' => 'required',
            'fecal_coliform' => 'required',
            'e_coli' => 'required',
            'total_coliform_bacteria' => 'required',
        ];
    }
}
